name: Fetch and Summarize AI Paper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 5'  # Every Friday at 08:00 CET (06:00 UTC)

jobs:
  fetch:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip install requests

      - name: Run fetch script
        run: python fetch_paper.py

      - name: Upload paper artifact
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: paper_to_summarize.json

  summarize:
    needs: fetch
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download paper artifact
        uses: actions/download-artifact@v4
        with:
          name: paper
          path: .

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip install transformers torch requests

      - name: Run summarize script
        run: python summarize_and_publish.py

      - name: Upload generated post artifact
        uses: actions/upload-artifact@v4
        with:
          name: ai-post
          path: data-blog/posts/*.qmd

      - name: Push post to data-blog repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          # Clone target repo
          git clone https://github.com/Flazoukie/data-blog.git target_repo
          cp data-blog/posts/*.qmd target_repo/posts/

          cd target_repo
          git add posts/
          git commit -m "🤖 New AI Summary Post - $(date +'%Y-%m-%d')" || echo "Nothing to commit"
          git push
        env:
          GIT_AUTHOR_NAME: github-actions
          GIT_AUTHOR_EMAIL: github-actions@github.com
          GIT_COMMITTER_NAME: github-actions
          GIT_COMMITTER_EMAIL: github-actions@github.com
          # Use the secret token
          GH_TOKEN: ${{ secrets.BLOG_PAT }}
        shell: bash
