name: Fetch and Summarize AI Paper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 5'  # Friday 08:00 CET = 06:00 UTC

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip install requests

      - name: Run fetch script
        run: python fetch_paper.py

      - name: Upload paper artifact
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: paper_to_summarize.json

  summarize:
    needs: fetch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download paper artifact
        uses: actions/download-artifact@v4
        with:
          name: paper
          path: .

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install transformers torch requests

      - name: Run summarize script
        run: python summarize_and_publish.py

      - name: Upload generated post artifact
        uses: actions/upload-artifact@v4
        with:
          name: ai-post
          path: ../data-blog/posts/*.qmd
